[extensions]
name = "Opti"
version = "1.0.0"
description = "Optifine alternatives"

[[mod]]
name = "Entity Model Features"
[mod.fabric]
"1.21.10" = "https://modrinth.com/mod/entity-model-features"
"1.21.1" = "https://modrinth.com/mod/entity-model-features"
"1.20.1" = "https://modrinth.com/mod/entity-model-features"
[mod.neoforge]
"1.21.1" = "https://modrinth.com/mod/entity-model-features"
[mod.forge]
"1.20.1" = "https://modrinth.com/mod/entity-model-features"

[[mod]]
name = "Entity Texture Features"
[mod.fabric]
"1.21.10" = "https://modrinth.com/mod/entitytexturefeatures"
"1.21.1" = "https://modrinth.com/mod/entitytexturefeatures"
"1.20.1" = "https://modrinth.com/mod/entitytexturefeatures"
[mod.neoforge]
"1.21.1" = "https://modrinth.com/mod/entitytexturefeatures"
[mod.forge]
"1.20.1" = "https://modrinth.com/mod/entitytexturefeatures"

[[mod]]
name = "Entity Sound Features"
[mod.fabric]
"1.21.1" = "https://modrinth.com/mod/esf"
"1.20.1" = "https://modrinth.com/mod/esf"
[mod.neoforge]
"1.21.1" = "https://modrinth.com/mod/esf"
[mod.forge]
"1.20.1" = "https://modrinth.com/mod/esf"

[[mod]]
name = "Polytone"
[mod.fabric]
"1.21.1" = "https://modrinth.com/mod/polytone"
"1.20.1" = "https://modrinth.com/mod/polytone"
[mod.neoforge]
"1.21.1" = "https://modrinth.com/mod/polytone"
[mod.forge]
"1.20.1" = "https://modrinth.com/mod/polytone"

[[mod]]
name = "Zume"
[mod.fabric]
"1.21.10" = "https://modrinth.com/mod/zume"
"1.21.1" = "https://modrinth.com/mod/zume"
"1.20.1" = "https://modrinth.com/mod/zume"
[mod.neoforge]
"1.21.1" = "https://modrinth.com/mod/zume"
[mod.forge]
"1.20.1" = "https://modrinth.com/mod/zume"

[[mod]]
name = "Nuit (formerly FabricSkyboxes)"
[mod.fabric]
"1.20.1" = "https://modrinth.com/mod/nuit"

[[mod]]
name = "Nuit Interop (formerly FabricSkyBoxes Interop)"
[mod.fabric]
"1.20.1" = "https://modrinth.com/mod/nuit-interop"

[[mod]]
name = "Optiboxes"
[mod.fabric]
"1.21.1" = "https://modrinth.com/mod/optiboxes"
"1.21.10" = "https://modrinth.com/mod/optiboxes"

[[mod]]
name = "CIT Resewn"
[mod.fabric]
"1.21.1" = "https://modrinth.com/mod/cit-resewn"
"1.20.1" = "https://modrinth.com/mod/cit-resewn"

[[mod]]
name = "OptiGUI"
[mod.fabric]
"1.21.10" = "https://modrinth.com/mod/optigui"
"1.21.1" = "https://modrinth.com/mod/optigui"
"1.20.1" = "https://modrinth.com/mod/optigui"

[[mod]]
name = "Continuity"
[mod.fabric]
"1.21.1" = "https://modrinth.com/mod/continuity"
"1.20.1" = "https://modrinth.com/mod/continuity"
[mod.neoforge]
"1.21.1" = "https://modrinth.com/mod/continuity"
[mod.forge]
"1.20.1" = "https://modrinth.com/mod/continuity"

[[mod]]
name = "Capes"
[mod.fabric]
"1.21.10" = "https://modrinth.com/mod/capes"
"1.21.1" = "https://modrinth.com/mod/capes"
"1.20.1" = "https://modrinth.com/mod/capes"

[[mod]]
name = "animatica"
[mod.fabric]
"1.21.1" = "https://modrinth.com/mod/animatica"
"1.20.1" = "https://modrinth.com/mod/animatica"

[[mod]]
name = "Dynamic Lights"
[mod.fabric]
# LambDynamicLights
"1.21.10" = "https://modrinth.com/mod/lambdynamiclights"
"1.21.1" = "https://modrinth.com/mod/lambdynamiclights"
"1.20.1" = "https://modrinth.com/mod/lambdynamiclights"
[mod.neoforge]
# LambDynamicLights
"1.21.1" = "https://modrinth.com/mod/lambdynamiclights"
[mod.forge]
# Dynamic Lights by Modrinth user "pauljoda"
"1.20.1" = "https://modrinth.com/datapack/dynamic-lights/version/1.9+mod"