name = "Taichi"
author = "OrzMiku"
version = "1.0.0-alpha.2+mc1.21.1_fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "316f03dd149f40e3244816571e565a8a7d41af087624912845ef751df3a65513"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
