name = "Taichi"
author = "OrzMiku"
version = "1.0.0-alpha.2+mc1.21.1_neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab33d079860f5397eaac3db0dc4322a372fdc948c6069ea13281cb60c4081715"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.208"
