name = "Taichi"
author = "OrzMiku"
version = "1.0.0-alpha.2+mc1.21.8_fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ea9b915ee9716b82cdb232b1118eae94eee630cfd3e41c19a3fab4e0b807a3f"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
