name = "Taichi"
author = "OrzMiku"
version = "1.0.0-alpha.2+mc1.20.1_fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1887b790cd27ad01b485150274a6498c8419ac5cf4c788a9ec4dcd913700e2df"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
