name = "Taichi"
author = "OrzMiku"
version = "1.0.0-alpha.1+mc1.21.8_neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13b7246df2aca4c4b0b24d10b4f48045ed0629c76b0be5151060f2f53a1adad7"

[versions]
minecraft = "1.21.8"
neoforge = "21.8.46"
