name = "Taichi"
author = "OrzMiku"
version = "1.0.0-alpha.2+mc1.21.8_neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b79f942df4f73db02046ad3defa98d7edfd4f5fa9114ea8c83ee12eaede95455"

[versions]
minecraft = "1.21.8"
neoforge = "21.8.46"
