name = "Taichi"
author = "OrzMiku"
version = "1.0.0-alpha.2+mc1.21.8_neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "200b0102a3f259b81285f5a3444016ac18b08728c84284c82818eadae4f0a7b0"

[versions]
minecraft = "1.21.8"
neoforge = "21.8.46"
